### ISSUE TITLE
Linting less as css

### ISSUE THREAD

**Issue by RedHatter** [sveltejs/svelte-atom#1]
I use less in my style tags and `svelte-atom` attempts to lint it as normal css.

**Comment by b-fuze** [comment]
Add `type="text/less"` or `lang="less"` to your `<style>`

**Comment by RedHatter** [comment]
I already have `lang="less"`

**Comment by b-fuze** [comment]
I see, the difference it makes for me is that the language highlight works and 10+ errors become one. Doesn't solve the issue, but less noise for me is better than nothing.

**Comment by b-fuze** [comment]
This is actually a [Language Server](https://github.com/UnwrittenFun/svelte-language-server) issue, I just observed the same behaviour in VSCode.

**Comment by rixo** [comment]
I believe Language Server update in the last version of the plugin has fixed this long standing issue. I don't see lint error after a quick test with the new version (setting `lang="lesse"` and using a less specific variable).
