### ISSUE TITLE
Svelte 3 support?

### ISSUE THREAD

**Issue by RedHatter** [sveltejs/svelte-atom#3]
This plugin doesn't seem to support svelte 3. (I got a linting error "directive values should not be wrapped")

**Comment by SKalt** [comment]
Same: I'm getting `A component can only have a default export`.

**Comment by rixo** [comment]
Svelte 3 was very partially supported by this package indeed.

The new 1.0.0 version brings up to date Language Server and grammar, which should fix most of the existing issues in this regard.
