### ISSUE TITLE
Open up html tags on enter

### ISSUE THREAD

**Issue by marcusnewton** [sveltejs/svelte-atom#4]
I'm too much of an idiot to fix it myself. 

```html
// the symbol | denotes where the cursor is

<div>|</div>
```

Pressing enter should do this:
```html
<div>
    |
</div>
```

Currently it does this:
```html
<div>
|</div>
```

**Comment by rixo** [comment]
I don't think this is a responsibility of this plugin, that's more of an editor concern. I see the same behaviour you describe in an simple HTML file. I don't know of any editor settings in Atom that would do that, but maybe you can find a plugin that implements the feature.
