### ISSUE TITLE
Syntax highlighting broken for Svelte 3

### ISSUE THREAD

**Issue by johannesmutter** [sveltejs/svelte-atom#8]
In Svelte 3 syntax highlighting doesn’t work properly:

<img width="487" alt="Bildschirmfoto 2020-04-02 um 17 14 27" src="https://user-images.githubusercontent.com/9489658/78265969-70719680-7505-11ea-9071-37565344fc90.png">

**Comment by the0neWhoKnocks** [comment]
Adding to the original post, these items break the syntax coloring:
- Using a [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)
- Destructuring within `each` clause

Things still compile correctly, but it's quite disappointing to have to choose between using newer supported features or using long-hand syntax to maintain highlighting consistency.

![svelte-broken-syntax-highlighting](https://user-images.githubusercontent.com/344140/146613902-ab6fc4ee-c389-4722-b60e-62c0b1729de6.gif)

**Comment by the0neWhoKnocks** [comment]
@johannesmutter Perhaps you should update the title of this ticket to "Syntax highlighting broken for Svelte 3" so that it's more easily discoverable.

**Comment by rixo** [comment]
A new version of the package has just been released with a major update of Language Server, and a brand new grammar ported from the VSCode extension one.

These changes should solve the problems mentioned in this thread. The grammar is still freshly backed and might have some defect, so you're very welcome to open other issues if you encounter new problems.
