### ISSUE TITLE
Commentting with cmd+/ applies html comments

### ISSUE THREAD

**Issue by jerrythomas** [sveltejs/svelte-atom#9]
In any svelte component. 

Press command + / on the code within the script or style tags. The code gets commented using html comments  instead of // for the script and /* */ for the css.

**Comment by mlsvrts** [comment]
I checked this, and it seems to be fixed by using an upgraded version of the language server (0.11.0). You can upgrade the package version yourself, or just use my fork instead. See https://github.com/sveltejs/svelte-atom/issues/2#issuecomment-751868920

**Comment by rixo** [comment]
Should be fixed in 1.0.0.

I now get proper comment format in script / markup / css.
